services:
  postgres:
    container_name: spring-redis-postgres-sorokin
    image: postgres:17.0
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - ./dbscript/base-seed.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    mem_limit: 128m

  redis:
    container_name: spring-redis-sorokin
    image: redis:8.2.1
    restart: on-failure
    ports:
      - "6379:6379"
    volumes:
      - redis_date:/data

volumes:
  postgres_data:
  redis_date: